/// <reference types="cypress" />

before(() => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin')
    cy.get('[name="password"]').type('admin123')
    cy.get('.orangehrm-login-button').click()
    cy.get('.oxd-main-menu-search > .oxd-input').type('PIM')
    cy.get('ul.oxd-main-menu').find('li').click()
    cy.get('.orangehrm-header-container > .oxd-button').click()
    cy.get('.--name-grouped-field > :nth-child(1)').find('.oxd-input').type('Teste')
    cy.get('.--name-grouped-field > :nth-child(3)').find('.oxd-input').type('Pureza')
    cy.get('.oxd-grid-2 > .oxd-grid-item > .oxd-input-group').find('.oxd-input').clear().type('2305')
    cy.get('.oxd-button--secondary').click()
    cy.get('.orangehrm-edit-employee-name > .oxd-text').should('have.text', "Teste Pureza")
})

it ('1. Pesquisar um employee pelo nome', function () {
    cy.get('.oxd-main-menu-search > .oxd-input').type('PIM')
    cy.get('ul.oxd-main-menu').find('li').click()
    cy.get(':nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-autocomplete-wrapper > .oxd-autocomplete-text-input > input').type('Teste Pureza')
    cy.get('.oxd-form-actions > .oxd-button--secondary').click()
    cy.get('.oxd-table-card > .oxd-table-row').should('have.length', 1)
    cy.get('.oxd-table-card > .oxd-table-row > :nth-child(2)').should('have.text', '2305')
    cy.get('.oxd-table-card > .oxd-table-row > :nth-child(3)').should('contains.text', 'Teste')
    cy.get('.oxd-table-card > .oxd-table-row > :nth-child(4)').should('contains.text', 'Pureza')
})

it ('2. Pesquisar um employee pelo ID', function() {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin')
    cy.get('[name="password"]').type('admin123')
    cy.get('.orangehrm-login-button').click()
    cy.get('.oxd-main-menu-search > .oxd-input').type('PIM')
    cy.get('ul.oxd-main-menu').find('li').click()
    cy.get(':nth-child(2) > .oxd-input').type('2305')
    cy.get('.oxd-form-actions > .oxd-button--secondary').click()
    cy.get('.oxd-table-card > .oxd-table-row').should('have.length', 1)
    cy.get('.oxd-table-card > .oxd-table-row > :nth-child(2)').should('have.text', '2305')
    cy.get('.oxd-table-card > .oxd-table-row > :nth-child(3)').should('contains.text', 'Teste')
    cy.get('.oxd-table-card > .oxd-table-row > :nth-child(4)').should('contains.text', 'Pureza')
})

it ('3. Pesquisar um employee com nome inexistente', function() {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin')
    cy.get('[name="password"]').type('admin123')
    cy.get('.orangehrm-login-button').click()
    cy.get('.oxd-main-menu-search > .oxd-input').type('PIM')
    cy.get('ul.oxd-main-menu').find('li').click()
    cy.get(':nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-autocomplete-wrapper > .oxd-autocomplete-text-input > input').type('Zoh Shia')
    cy.get('.oxd-form-actions > .oxd-button--secondary').click()
    cy.get('.oxd-table-card > .oxd-table-row').should('have.length', 0)
})

it ('4. Pesquisar um employee com ID inexistente', function() {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('[name="username"]').type('Admin')
    cy.get('[name="password"]').type('admin123')
    cy.get('.orangehrm-login-button').click()
    cy.get('.oxd-main-menu-search > .oxd-input').type('PIM')
    cy.get('ul.oxd-main-menu').find('li').click()
    cy.get(':nth-child(2) > .oxd-input').type('0666')
    cy.get('.oxd-form-actions > .oxd-button--secondary').click()
    cy.get('.oxd-table-card > .oxd-table-row').should('have.length', 0)
})

after(() => {
    cy.get('.oxd-main-menu-search > .oxd-input').type('PIM')
    cy.get('ul.oxd-main-menu').find('li').click()
    cy.get(':nth-child(2) > .oxd-input').type('2305')
    cy.get('.oxd-form-actions > .oxd-button--secondary').click()
    cy.wait(2000)
    cy.get('.oxd-table-cell-actions > :nth-child(2) > .oxd-icon').click()
    cy.get('.oxd-button--label-danger').click()
})